baseURL: "https://thepirateship.dev/"
title: The Pirate Ship
paginate: 5
theme: PaperMod-5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


minify:
    disableXML: true
    minifyOutput: true

params:
    env: production
    title: The Pirate Ship
    description: "A place where Pirates can learn more about interesting coding topics."
    keywords: [Cryptocurrency, Parallax, GitHub, TradingView]
    author: Pirate
    images: ["/authors/pirate.png"]
    DateFormat: "January 2, 2006"
    defaultTheme: dark
    disableThemeToggle: true
    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: true
    showtoc: false
    tocopen: true

    assets:
        favicon: "/logo.svg"
        favicon16x16: "/logo.svg"
        favicon32x32: "/logo.svg"
        apple_touch_icon: "/logo.svg"
        safari_pinned_tab: "/logo.svg"

    label:
        text: "The Pirate Ship"

    profileMode:
        enabled: true
        subtitle: "A collection of research and code for cryptocurrencies."
        imageUrl: "/logo.svg" # optional
        imageWidth: 240 # custom size
        imageHeight: 240 # custom size
        buttons:
            - name: News
              url: "/news"
            - name: Indicators
              url: "/indicators"
            - name: Guides
              url: "/guides"
            - name: Cryptos
              url: "/cryptos"
            - name: NFTs
              url: "/nfts"

menu:
    main:
        - identifier: news
          name: News
          url: /news/
          weight: 1
        - identifier: indicators
          name: Indicators
          url: /indicators/
          weight: 2
        - identifer: guides
          name: Guides
          url: /guides/
          weight: 3
        - identifier: cryptos
          name: Cryptos
          url: /cryptos/
          weight: 4
        - identifier: nfts
          name: NFTs
          url: /nfts/
          weight: 5

taxonomies:
    category: categories
    tag: tags
