baseURL: "https://thepirateship.dev/"
title: The Pirate Ship
paginate: 5
theme: PaperMod-5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false


minify:
    disableXML: true
    minifyOutput: true

params:
    env: production
    title: The Pirate Ship
    description: "A place where Pirates can learn more about interesting coding topics."
    keywords: [Cryptocurrency, Parallax, GitHub, TradingView]
    author: Pirate
    images: ["/authors/pirate.png"]
    DateFormat: "January 2, 2006"
    defaultTheme: dark
    disableThemeToggle: true
    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: true
    showtoc: false
    tocopen: true

    assets:
        favicon: "/logo/logo.svg"
        favicon16x16: "/logo/logo.svg"
        favicon32x32: "/logo/logo.svg"
        apple_touch_icon: "/logo/logo.svg"
        safari_pinned_tab: "/logo/logo.svg"

    label:
        text: "The Pirate Ship"

    profileMode:
        enabled: true
        subtitle: "A collection of research and code for cryptocurrencies."
        imageUrl: "/logo/logo.svg" # optional
        imageWidth: 240 # custom size
        imageHeight: 240 # custom size
        buttons:
            - name: Announcements
              url: "/announcements"
            - name: Indicators
              url: "/indicators"
            - name: Cryptocurrency
              url: "/cryptocurrency"

menu:
    main:
        - identifier: announcements
          name: Announcements
          url: /announcements/
          weight: 1
        - identifier: indicators
          name: Indicators
          url: /indicators/
          weight: 2
        - identifier: cryptocurrency
          name: Cryptocurrency
          url: /cryptocurrency/
          weight: 3

taxonomies:
    category: categories
    tag: tags